<a href="https://colab.research.google.com/github/Rosch0/Data-Science/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1D

In [ ]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
x.size

2

In [ ]:
x.shape


(2,)

In [ ]:
x.dtype

dtype('int64')

# Tablice 2d

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

# 3D

In [ ]:
x = np.array(
    [[[4, 3, 1],
       [3, 1, 2]],

      [[4, 1, 3],
       [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.shape


(2, 2, 3)

# typy danych

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.4], dtype='complex')
A.dtype

dtype('complex128')

Tworzenie tablic


# Nowa sekcja Tworzenie tablic


In [ ]:
import numpy as np

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#Podstawowe operacje na tablicach

In [ ]:
import numpy as np

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B #dodawanie tablic


array([6, 0, 7, 4])

In [ ]:
A - B #odejmowanie tablic

array([0, 2, 1, 0])

In [ ]:
A * B #mnożenie tablic


array([ 9, -1, 12,  4])

In [ ]:
A / B #dzielenie przez tablice

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B) #metoda na dodawanie tablic

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B) #Metoda odejmowania tablic

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B) #Metoda mnożenia tablic

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B) #Metoda dzielenia tablic

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3 #dodawanie stałej

array([6, 4, 7, 5])

In [ ]:
A + 3 * B

array([12, -2, 13,  8])

In [ ]:
x = np.array([[1,3], [-2, 0] ]) #macież kwadratowa
y = np. array([[6, 0], [-1, 2]]) #macież kwadratowa
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
x * y #mnożenie po elemencie (nie jak macieże)

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(x, y) #MNOŻENIE MACIEŻY POPRAWNE

array([[  3,   6],
       [-12,   0]])

In [ ]:
x.dot(y) #MNOŻENIE MACIEŻY W INNY SPOSÓB

array([[  3,   6],
       [-12,   0]])

In [ ]:
y.dot(x) #MNOŻENIE MACIEŻY W INNY SPOSÓB

array([[ 6, 18],
       [-5, -3]])

In [ ]:
x @ y #MNOŻENIE MACIEŻY PRZEDSTAWIONE INACZEJ

array([[  3,   6],
       [-12,   0]])

# Generowanie liczb pseudolosowych

In [ ]:
import numpy as np

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn(5) #podaje losową liczbę z rozkładu normalnego

array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799])

In [ ]:
np.random.randn(10, 4)

array([[-0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218]])

In [ ]:
np.random.rand()

0.6531083254653984

In [ ]:
np.random.randint(10) # losuje liczbę z liczby rzeczywistej w tym przypadku od 0 do 10

3

In [ ]:
np.random.randint(low=10, high=101, size=10) #generuje od 10 do 101 oraz podaje 10 liczb wylosowanych

array([74, 79, 10, 60, 46, 44, 58, 13, 52, 87])

In [ ]:
np.random.choice([4, 2, 1, 4]) #choice zwraca losowy element z tej podanej listy (może też zwracać słowa)

4

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data) #tasuje dane które są podane
data

array([3, 7, 4, 5, 9, 1, 0, 6, 2, 8])

# Podstawowe funkcje w NumPy

In [ ]:
import numpy as np

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9) #Pierwiastek kwadratowy z przekazanej liczby

3.0

In [ ]:
np.all([2, 3, 1]) #testuje to co w listach lub tablicach i jeśli wszystko jest True zwraca True

True

In [ ]:
np.any([3, 4, 1]) #testuje i zwraca true jeśli jakikolwiek obiekt jest true

In [ ]:
bool(0) #zwraca wartość logiczną obiektu jeśli 0 zawsze False

True

In [ ]:
A = np.random.rand(5)
A

array([0.38240493, 0.69601978, 0.06416992, 0.83042412, 0.82657873])

In [ ]:
np.argmax(A) #funkcja zwraca największą wartość z wybranej funkcji lub tabeli

3

In [ ]:
A[np.argmax(A)] #wycinanie w inny sposób wartość największą

0.8304241172613847

In [ ]:
np.argmin(A) #zwraca wartość najniższą

2

In [ ]:
A[np.argmin(A)] #wycinanie w inny sposób wartość najniższą

0.06416991868498667

In [ ]:
np.argsort(A) #pozwala sortować elementy podając indeks

array([2, 0, 1, 4, 3])

In [ ]:
A[np.argsort(A)]

array([0.06416992, 0.38240493, 0.69601978, 0.82657873, 0.83042412])

*kursywa*# Indeksowanie i wycinanie tablic

# Indeksowanie i wycinanie tablic

In [ ]:
import numpy as np

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop] -indeksowanie
A[2] # Wycinanie drugiego indeksu

2

In [ ]:
A[2:] # wycinanie wszystkiego od dwójki w górę

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2] #Wycinanie od 2 do początku bez tego 2

array([0, 1])

In [ ]:
A[[0, 1, 2]] #Wycinanie konkretnej listy indeksów

array([0, 1, 2])

In [ ]:
A[10:15] #Od do

array([10, 11, 12, 13, 14])

In [ ]:
A = A.reshape(4, 5) #Zmiana kształtu tablicy 4x5
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1] #Teraz z innym kształtem tablicy wycinamy wiersze

array([5, 6, 7, 8, 9])

In [ ]:
A[:,1] #Wycinanie kolumny

array([ 1,  6, 11, 16])

In [ ]:
A[1,1] #Wycinanie konkretnej rzeczy z kolumny 1 i wierszu 1

6

In [ ]:
A [1:2, 2:4] #Wycinanie od do

array([[7, 8]])

In [ ]:
A[1, 2] = 14 #Zmiana wartości w konkretnym miejscu
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#  Iteracja po tablicach, zmiana rozmiaru oraz maski logiczne

In [ ]:
import numpy as np


In [ ]:
A = np.arange(20)

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row[0]) #indeksowanie po tabelach

In [ ]:
for item in A.flat:
  print(item) #indeks poszczegulnych rzeczy

ZMIANA ROZMIARU TABLIC

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel() #powrót do płaskiej postaci tablicy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T #transponowanie tablicy

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

MASKI LOGICZNE

In [ ]:
A = np.arange(start= -10, stop=10, step=0.5)
A = A.reshape(10, -1)
A
#Budowa tablicy od -10 do 10 co 0.5 w kolumnach

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0 #równanie maski logicznej która pokazuje która liczba jest dodatnia

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A > 0] #Wycięcie elementów które nas interesuje

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A > -5, A < 5) # łączenie masek oba warunki spełnione

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])